language: java
jdk:
  - oraclejdk8
  - openjdk8
sudo: true
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
- rm -f $HOME/.gradle/caches/*/*.lock
before_install:
- chmod +x gradlew
